/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 computer-optimized.glb -T 
Files: computer-optimized.glb [486.38KB] > /home/jeremy/Projects/github_projects/portfolio/public/models/computer-optimized-transformed.glb [39.72KB] (92%)
*/

import { useGLTF } from '@react-three/drei'
import type { JSX } from 'react/jsx-runtime'
import * as THREE from 'three'

export function Computer(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF('/models/computer-optimized-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-4.005, 67.549, 58.539]}>
        <mesh castShadow receiveShadow geometry={(nodes.Cube000_ComputerDesk_0001_1 as THREE.Mesh).geometry} material={materials['ComputerDesk.001']} />
        <mesh castShadow receiveShadow geometry={(nodes.Cube000_ComputerDesk_0001_2 as THREE.Mesh).geometry} material={materials['FloppyDisk.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/computer-optimized-transformed.glb')
